### PR TITLE
Upgrade Tailwind

### LINKED ISSUE #11: Upgrade Tailwind

### PR DESCRIPTION
**Pull request by SL0wZEr**
This PR upgrades Tailwind, and closes #11.

Here are some things I wasn't sure about 👀

- What the anchors' color should be, as Tailwind no longer uses the default blue and I didn't want to just create new color.
- With this upgrade, we're still unable to use the new Tailwind's colors as `text-gray-100` because I overrode the defaults. I'll move the used `colors` and `screens` to `extend` section in a different PR. But then I had to either choose a close `indigo` color (Tailwind's default indigo seems more saturated) or introduce new one and name it `indigo-base`. Not sure 🤷🏻‍♂️.

### CODE REVIEW

**Comment by mattstauffer** [comment]
Thanks for this!

Looks like we're using `text-indigo` on at least some links, so we may want to just use that?

image

Would you mind showing me a screenshot of what it looks like with the new indigo?

**Comment by SL0wZEr** [comment]
@mattstauffer Here's a screenshot.

Screen Shot 2020-02-10 at 11 06 09 PM

**Comment by SL0wZEr** [comment]
As for the `text-indigo`. The thing is, if we want to move `colors` under `extend` section (which is not at the moment), we can't have a color named just `indigo`. So `text-indigo` will not work any more. I'm not sure if I have clarified my point.. 

Screen Shot 2020-02-10 at 11 15 01 PM

**Comment by mattstauffer** [comment]
I'm fine with the intensity of that indigo-600 color.

So... is the goal here to manually set our own classes instead of switching all of our HTML to use the new color system?

**Comment by SL0wZEr** [comment]
I prefer to switch all HTML to use the new color system and choose the closest color for each.

Should this be done on this same PR?

**Comment by mattstauffer** [comment]
@SL0wZEr If you don't mind, that'd be great! :)

**Comment by SL0wZEr** [comment]
@mattstauffer Done. Only 3 custom colors were left. I Couldn't find any default alternative.

```
'custom-indigo-light': '#e6e8ff', // logo + Github icon
'custom-indigo-darker': '#2f365f', // footer
'custom-indigo-darkest': '#2b3158', // header
```

Here's a screenshot 

nova

**Comment by mattstauffer** [comment]
@SL0wZEr Thank you so much for your work on this!!

**Pull request merged**
