### PR TITLE
Redirect the user to their previous page after log in and registration

### LINKED ISSUE #3: After login not returning to previous page
From @RicardoRamirezR (tightenco/novapackages-issues#21):

Hi there,

It is redirected to home page.

Thank you for your work.

### PR DESCRIPTION
**Pull request by marcusmoore**
This PR stores the url that the user was at before they hit the `Log in / Register` link and redirects them back to that page after successful log in or registration.

Fixes #3

### CODE REVIEW

**Comment by mattstauffer** [comment]
Would it be possible to use `intended()` here? Or does that not work with Socialite? Thanks!

**Comment by marcusmoore** [comment]
@mattstauffer I just tried it and we can't used `intended()` in this case. 

I added a minor commit that redirects authenticated users that manually enter `{{ APP_URL}}/login/github` in their url bar. They were getting redirected to this page: 

image

Now they land on `/`.

In addition, I think we can get rid of the `HomeController` and `home` blade files as well but I'll let you decide if A) that's a good idea and B) if it should happen in this PR.

**Comment by mattstauffer** [comment]
@marcusmoore we can definitely delete those if we don't use em. :) separate PR please.

I believe that, even if we don't manually get `intended` defined, we can still *manually* set it, so that instead of using our own made-up key, we use the `url.intended` session key and then can call `intended()` on the other side. Can you test that out please?

**Comment by marcusmoore** [comment]
@mattstauffer good thinking. Updated 👍

**Comment by mattstauffer** [comment]
Great work!

**Pull request merged**
